
"""
train_baselines.py

Dedicated training and evaluation runner for the discrete-time competitor models:
  - DeepLOBBaseline
  - StaticGCNBaseline

Features:
  - Loads fold_XXX_train.npz and fold_XXX_test.npz generated by build_discrete_snapshots.py
  - Uses the same 3D volatility regression objective (MSE on rv_1s, rv_5s, rv_10s)
  - Chronological validation split + early stopping
  - Test metrics aligned with eval_runner.py:
      * RMSE
      * MAE
      * Spearman Rank IC
  - Multi-seed aggregation across 3-5 deterministic seeds
  - Writes baseline_metrics_summary.json in a merge-friendly format
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import os
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from scipy.stats import spearmanr
from torch import Tensor, nn

from src.utils.memory import log_memory
from src.utils.run_manifest import build_run_manifest, save_run_manifest
from torch.utils.data import DataLoader, Dataset, Subset

try:
    from src.utils.device import describe_device, resolve_device
    from src.utils.logging import format_mean_std, summary_dict_to_frame, write_json
    from src.utils.seeding import set_global_seed
except ImportError:  # pragma: no cover
    from utils.device import describe_device, resolve_device
    from utils.logging import format_mean_std, summary_dict_to_frame, write_json
    from utils.seeding import set_global_seed


# ---------------------------------------------------------------------
# Dynamic import of baselines.py
# ---------------------------------------------------------------------

def _load_baselines_module(module_path: str):
    module_path = os.path.abspath(module_path)
    spec = importlib.util.spec_from_file_location("lob_baselines", module_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load baselines module from {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------

def set_seed(seed: int) -> None:
    set_global_seed(seed, deterministic=True)


# ---------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------

RV_NAMES = ["1s", "5s", "10s"]


def rmse(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.sqrt(np.mean((y_true - y_pred) ** 2)))


def mae(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.mean(np.abs(y_true - y_pred)))


def safe_spearman(x: np.ndarray, y: np.ndarray) -> float:
    if x.size == 0 or y.size == 0:
        return 0.0
    if np.allclose(x, x[0]) or np.allclose(y, y[0]):
        return 0.0
    val = spearmanr(x, y).correlation
    if val is None or np.isnan(val):
        return 0.0
    return float(val)


# ---------------------------------------------------------------------
# Datasets
# ---------------------------------------------------------------------

class DeepLOBDataset(Dataset):
    def __init__(self, npz_path: str):
        data = np.load(npz_path)
        self.X = torch.tensor(data["X"], dtype=torch.float32)           # [N, T, 40]
        self.y = torch.tensor(data["y"], dtype=torch.float32)           # [N, 3]
        self.t_us = data["t_us"].astype(np.int64)
        self.event_id = data["event_id"].astype(np.int64)

    def __len__(self) -> int:
        return int(self.X.shape[0])

    def __getitem__(self, idx: int):
        return {
            "X": self.X[idx],
            "y": self.y[idx],
            "t_us": int(self.t_us[idx]),
            "event_id": int(self.event_id[idx]),
        }


class StaticGCNDataset(Dataset):
    def __init__(self, npz_path: str):
        data = np.load(npz_path)
        self.node_x = torch.tensor(data["node_x"], dtype=torch.float32)  # [N, 20, F_node]
        self.y = torch.tensor(data["y"], dtype=torch.float32)            # [N, 3]
        self.t_us = data["t_us"].astype(np.int64)
        self.event_id = data["event_id"].astype(np.int64)

    def __len__(self) -> int:
        return int(self.node_x.shape[0])

    def __getitem__(self, idx: int):
        return {
            "node_x": self.node_x[idx],
            "y": self.y[idx],
            "t_us": int(self.t_us[idx]),
            "event_id": int(self.event_id[idx]),
        }


# ---------------------------------------------------------------------
# Fold path helpers
# ---------------------------------------------------------------------

def discover_fold_ids(data_dir: str, model_name: str) -> List[int]:
    subdir = Path(data_dir) / model_name
    if not subdir.exists():
        raise FileNotFoundError(f"Missing baseline data subdir: {subdir}")

    fold_ids = set()
    for path in subdir.glob("fold_*_train.npz"):
        stem = path.stem
        # fold_001_train -> 001
        parts = stem.split("_")
        if len(parts) >= 3:
            try:
                fold_ids.add(int(parts[1]))
            except ValueError:
                pass

    if not fold_ids:
        raise ValueError(f"No fold_XXX_train.npz files found under {subdir}")

    return sorted(fold_ids)


def fold_npz_paths(data_dir: str, model_name: str, fold_id: int) -> Tuple[str, str]:
    fold_name = f"fold_{fold_id:03d}"
    train_path = os.path.join(data_dir, model_name, f"{fold_name}_train.npz")
    test_path = os.path.join(data_dir, model_name, f"{fold_name}_test.npz")
    if not os.path.exists(train_path):
        raise FileNotFoundError(train_path)
    if not os.path.exists(test_path):
        raise FileNotFoundError(test_path)
    return train_path, test_path


# ---------------------------------------------------------------------
# Validation split
# ---------------------------------------------------------------------

def chronological_train_val_split(
    dataset: Dataset,
    val_fraction: float = 0.2,
    min_val_samples: int = 32,
    purge_us: int = 10_000_000,
) -> Tuple[Subset, Subset]:
    n = len(dataset)
    if n < 2:
        raise ValueError("Need at least 2 samples for train/val split.")
    if not hasattr(dataset, "t_us"):
        raise TypeError("Dataset must expose a chronological t_us array for purged validation.")

    val_n = max(min_val_samples, int(round(n * val_fraction)))
    val_n = min(val_n, max(1, n - 1))
    val_start_idx = n - val_n
    t_us = np.asarray(getattr(dataset, "t_us"), dtype=np.int64)
    val_start_t = int(t_us[val_start_idx])
    train_n = int(np.searchsorted(t_us, val_start_t - int(purge_us), side="left"))
    if train_n <= 0:
        raise ValueError("Purged validation left no training samples. Increase fold size or reduce purge_us.")

    train_idx = list(range(0, train_n))
    val_idx = list(range(val_start_idx, n))
    return Subset(dataset, train_idx), Subset(dataset, val_idx)


# ---------------------------------------------------------------------
# Dataloaders
# ---------------------------------------------------------------------

def collate_deeplob(batch: List[Dict[str, object]]) -> Dict[str, Tensor]:
    X = torch.stack([item["X"] for item in batch], dim=0)
    y = torch.stack([item["y"] for item in batch], dim=0)
    t_us = torch.tensor([item["t_us"] for item in batch], dtype=torch.long)
    event_id = torch.tensor([item["event_id"] for item in batch], dtype=torch.long)
    return {"X": X, "y": y, "t_us": t_us, "event_id": event_id}


def collate_static_gcn(batch: List[Dict[str, object]]) -> Dict[str, Tensor]:
    node_x = torch.stack([item["node_x"] for item in batch], dim=0)
    y = torch.stack([item["y"] for item in batch], dim=0)
    t_us = torch.tensor([item["t_us"] for item in batch], dtype=torch.long)
    event_id = torch.tensor([item["event_id"] for item in batch], dtype=torch.long)
    return {"node_x": node_x, "y": y, "t_us": t_us, "event_id": event_id}


# ---------------------------------------------------------------------
# Training / evaluation
# ---------------------------------------------------------------------

@dataclass
class RunnerConfig:
    data_dir: str
    baselines_module_path: str

    model_name: str                  # deeplob or static_gcn
    device: str = "cpu"

    batch_size: int = 64
    num_workers: int = 0
    epochs: int = 30
    patience: int = 5
    val_fraction: float = 0.2
    min_val_samples: int = 32
    purge_us: int = 10_000_000

    lr: float = 1e-3
    weight_decay: float = 1e-5
    grad_clip_norm: float = 1.0

    seeds: Tuple[int, ...] = (42, 43, 44)

    # Model kwargs
    deeplob_input_dim: int = 40
    deeplob_conv_channels: int = 32
    deeplob_inception_branch_channels: int = 16
    deeplob_lstm_hidden_dim: int = 64
    deeplob_lstm_layers: int = 1
    deeplob_regression_hidden_dim: int = 128
    deeplob_dropout: float = 0.1

    static_gcn_node_feat_dim: int = 5
    static_gcn_num_levels: int = 10
    static_gcn_hidden_dim: int = 64
    static_gcn_num_layers: int = 3
    static_gcn_dropout: float = 0.1
    static_gcn_regression_hidden_dim: int = 128

    out_dir: Optional[str] = None


def build_model(cfg: RunnerConfig, baselines_module) -> nn.Module:
    if cfg.model_name == "deeplob":
        model = baselines_module.DeepLOBBaseline(
            input_dim=cfg.deeplob_input_dim,
            conv_channels=cfg.deeplob_conv_channels,
            inception_branch_channels=cfg.deeplob_inception_branch_channels,
            lstm_hidden_dim=cfg.deeplob_lstm_hidden_dim,
            lstm_layers=cfg.deeplob_lstm_layers,
            regression_hidden_dim=cfg.deeplob_regression_hidden_dim,
            dropout=cfg.deeplob_dropout,
            out_dim=3,
        )
        return model

    if cfg.model_name == "static_gcn":
        model = baselines_module.StaticGCNBaseline(
            node_feat_dim=cfg.static_gcn_node_feat_dim,
            num_levels=cfg.static_gcn_num_levels,
            hidden_dim=cfg.static_gcn_hidden_dim,
            num_gcn_layers=cfg.static_gcn_num_layers,
            graph_dropout=cfg.static_gcn_dropout,
            regression_hidden_dim=cfg.static_gcn_regression_hidden_dim,
            out_dim=3,
        )
        return model

    raise ValueError(f"Unknown model_name={cfg.model_name}")


def model_forward(
    model: nn.Module,
    batch: Dict[str, Tensor],
    cfg: RunnerConfig,
    edge_index: Optional[Tensor] = None,
) -> Tensor:
    if cfg.model_name == "deeplob":
        return model(batch["X"])
    if cfg.model_name == "static_gcn":
        return model(batch["node_x"], edge_index=edge_index)
    raise ValueError(f"Unknown model_name={cfg.model_name}")


def train_one_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    cfg: RunnerConfig,
    device: torch.device,
    edge_index: Optional[Tensor] = None,
) -> float:
    model.train()
    total_loss = 0.0
    total_count = 0

    for batch in loader:
        optimizer.zero_grad()

        batch = {k: v.to(device) for k, v in batch.items()}
        pred = model_forward(model, batch, cfg, edge_index=edge_index)
        loss = F.mse_loss(pred, batch["y"])

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=cfg.grad_clip_norm)
        optimizer.step()

        bs = int(batch["y"].shape[0])
        total_loss += float(loss.item()) * bs
        total_count += bs

    return total_loss / max(total_count, 1)


@torch.no_grad()
def evaluate_loss(
    model: nn.Module,
    loader: DataLoader,
    cfg: RunnerConfig,
    device: torch.device,
    edge_index: Optional[Tensor] = None,
) -> float:
    model.eval()
    total_loss = 0.0
    total_count = 0

    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        pred = model_forward(model, batch, cfg, edge_index=edge_index)
        loss = F.mse_loss(pred, batch["y"])

        bs = int(batch["y"].shape[0])
        total_loss += float(loss.item()) * bs
        total_count += bs

    return total_loss / max(total_count, 1)


@torch.no_grad()
def evaluate_predictions(
    model: nn.Module,
    loader: DataLoader,
    cfg: RunnerConfig,
    device: torch.device,
    edge_index: Optional[Tensor] = None,
) -> Dict[str, object]:
    model.eval()

    y_true_list = []
    y_pred_list = []
    t_us_list = []
    event_id_list = []

    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        pred = model_forward(model, batch, cfg, edge_index=edge_index)

        y_true_list.append(batch["y"].cpu().numpy())
        y_pred_list.append(pred.cpu().numpy())
        t_us_list.append(batch["t_us"].cpu().numpy())
        event_id_list.append(batch["event_id"].cpu().numpy())

    if not y_true_list:
        raise ValueError("Empty evaluation loader.")

    y_true = np.concatenate(y_true_list, axis=0)
    y_pred = np.concatenate(y_pred_list, axis=0)
    t_us = np.concatenate(t_us_list, axis=0).astype(np.int64)
    event_id = np.concatenate(event_id_list, axis=0).astype(np.int64)

    metrics: Dict[str, float] = {}
    for i, h in enumerate(RV_NAMES):
        metrics[f"rmse_{h}"] = rmse(y_true[:, i], y_pred[:, i])
        metrics[f"mae_{h}"] = mae(y_true[:, i], y_pred[:, i])
        metrics[f"spearman_{h}"] = safe_spearman(y_pred[:, i], y_true[:, i])

    return {
        "metrics": metrics,
        "y_true": y_true,
        "y_pred": y_pred,
        "t_us": t_us,
        "event_id": event_id,
    }


# ---------------------------------------------------------------------
# Per-fold execution
# ---------------------------------------------------------------------

def make_dataloaders_for_fold(
    train_path: str,
    test_path: str,
    cfg: RunnerConfig,
) -> Tuple[Dataset, Dataset, Dataset, DataLoader, DataLoader, DataLoader]:
    if cfg.model_name == "deeplob":
        full_train_ds = DeepLOBDataset(train_path)
        test_ds = DeepLOBDataset(test_path)
        train_ds, val_ds = chronological_train_val_split(
            full_train_ds,
            val_fraction=cfg.val_fraction,
            min_val_samples=cfg.min_val_samples,
            purge_us=cfg.purge_us,
        )
        collate_fn = collate_deeplob

    elif cfg.model_name == "static_gcn":
        full_train_ds = StaticGCNDataset(train_path)
        test_ds = StaticGCNDataset(test_path)
        train_ds, val_ds = chronological_train_val_split(
            full_train_ds,
            val_fraction=cfg.val_fraction,
            min_val_samples=cfg.min_val_samples,
            purge_us=cfg.purge_us,
        )
        collate_fn = collate_static_gcn

    else:
        raise ValueError(f"Unknown model_name={cfg.model_name}")

    train_loader = DataLoader(
        train_ds,
        batch_size=cfg.batch_size,
        shuffle=True,
        num_workers=cfg.num_workers,
        collate_fn=collate_fn,
        drop_last=False,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
        collate_fn=collate_fn,
        drop_last=False,
    )
    test_loader = DataLoader(
        test_ds,
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
        collate_fn=collate_fn,
        drop_last=False,
    )

    return train_ds, val_ds, test_ds, train_loader, val_loader, test_loader


def train_one_fold(
    cfg: RunnerConfig,
    baselines_module,
    train_path: str,
    test_path: str,
    seed: int,
) -> Dict[str, object]:
    set_seed(seed)

    device = torch.device(resolve_device(cfg.device))
    model = build_model(cfg, baselines_module).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=cfg.lr,
        weight_decay=cfg.weight_decay,
    )

    train_ds, val_ds, test_ds, train_loader, val_loader, test_loader = make_dataloaders_for_fold(
        train_path=train_path,
        test_path=test_path,
        cfg=cfg,
    )

    edge_index = None
    if cfg.model_name == "static_gcn":
        edge_np = baselines_module.build_static_lob_edge_index(
            num_levels=cfg.static_gcn_num_levels,
            include_self_loops=False,
            device=device,
        )
        edge_index = edge_np

    best_val = float("inf")
    best_state = None
    best_epoch = -1
    epochs_no_improve = 0

    for epoch in range(1, cfg.epochs + 1):
        _ = train_one_epoch(
            model=model,
            loader=train_loader,
            optimizer=optimizer,
            cfg=cfg,
            device=device,
            edge_index=edge_index,
        )
        val_loss = evaluate_loss(
            model=model,
            loader=val_loader,
            cfg=cfg,
            device=device,
            edge_index=edge_index,
        )

        if val_loss < best_val - 1e-12:
            best_val = val_loss
            best_epoch = epoch
            epochs_no_improve = 0
            best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        else:
            epochs_no_improve += 1

        if epochs_no_improve >= cfg.patience:
            break

    if best_state is None:
        raise RuntimeError("Early stopping failed to capture a best model state.")

    model.load_state_dict(best_state)

    prediction_output = evaluate_predictions(
        model=model,
        loader=test_loader,
        cfg=cfg,
        device=device,
        edge_index=edge_index,
    )
    metrics = dict(prediction_output["metrics"])
    metrics["best_val_loss"] = float(best_val)
    metrics["best_epoch"] = int(best_epoch)
    metrics["num_train_samples"] = int(len(train_ds))
    metrics["num_val_samples"] = int(len(val_ds))
    metrics["num_test_samples"] = int(len(test_ds))
    return {
        "metrics": metrics,
        "predictions": {
            "event_id": prediction_output["event_id"],
            "t_us": prediction_output["t_us"],
            "y_true": prediction_output["y_true"],
            "y_pred": prediction_output["y_pred"],
        },
    }


# ---------------------------------------------------------------------
# Aggregation
# ---------------------------------------------------------------------

def aggregate_rows(rows: List[Dict[str, float]]) -> Dict[str, Dict[str, float]]:
    if not rows:
        raise ValueError("No rows to aggregate.")

    metric_keys = [k for k in rows[0].keys() if isinstance(rows[0][k], (int, float, np.floating, np.integer))]
    out: Dict[str, Dict[str, float]] = {}

    for key in metric_keys:
        vals = np.asarray([float(r[key]) for r in rows], dtype=np.float64)
        mean_val = float(np.mean(vals))
        std_val = float(np.std(vals, ddof=1)) if vals.size > 1 else 0.0
        out[key] = {
            "mean": mean_val,
            "std": std_val,
            "formatted": format_mean_std(mean_val, std_val),
        }
    return out


def build_summary_json(
    cfg: RunnerConfig,
    fold_seed_rows: List[Dict[str, object]],
    per_seed_rows: List[Dict[str, object]],
    overall_metrics: Dict[str, Dict[str, float]],
) -> Dict[str, object]:
    return {
        "model_name": cfg.model_name,
        "device": cfg.device,
        "seeds": list(cfg.seeds),
        "hyperparameters": {
            "batch_size": cfg.batch_size,
            "epochs": cfg.epochs,
            "patience": cfg.patience,
            "val_fraction": cfg.val_fraction,
            "min_val_samples": cfg.min_val_samples,
            "purge_us": cfg.purge_us,
            "lr": cfg.lr,
            "weight_decay": cfg.weight_decay,
            "grad_clip_norm": cfg.grad_clip_norm,
        },
        "per_fold_per_seed": fold_seed_rows,
        "per_seed_summary": per_seed_rows,
        "overall_summary": overall_metrics,
    }


# ---------------------------------------------------------------------
# Main experiment
# ---------------------------------------------------------------------

def run_baseline_experiment(cfg: RunnerConfig) -> Dict[str, object]:
    start_time = time.time()
    resolved_device = resolve_device(cfg.device)
    cfg = RunnerConfig(**{**asdict(cfg), "device": resolved_device})
    baselines_module = _load_baselines_module(cfg.baselines_module_path)
    fold_ids = discover_fold_ids(cfg.data_dir, cfg.model_name)

    print(describe_device(resolved_device))
    print(f"Baseline model: {cfg.model_name}")
    print(f"Purged folds: {len(fold_ids)}")

    fold_seed_rows: List[Dict[str, object]] = []
    per_seed_rows: List[Dict[str, object]] = []
    prediction_dir: Optional[str] = None
    if cfg.out_dir is not None:
        os.makedirs(cfg.out_dir, exist_ok=True)
        prediction_dir = os.path.join(cfg.out_dir, "predictions")
        os.makedirs(prediction_dir, exist_ok=True)

    for seed in cfg.seeds:
        seed_fold_metrics: List[Dict[str, float]] = []
        seed_y_true: List[np.ndarray] = []
        seed_y_pred: List[np.ndarray] = []

        for fold_id in fold_ids:
            train_path, test_path = fold_npz_paths(cfg.data_dir, cfg.model_name, fold_id)

            fold_output = train_one_fold(
                cfg=cfg,
                baselines_module=baselines_module,
                train_path=train_path,
                test_path=test_path,
                seed=seed,
            )
            metrics = fold_output["metrics"]

            row = {
                "seed": int(seed),
                "fold_id": int(fold_id),
                **{k: float(v) for k, v in metrics.items()},
            }
            fold_seed_rows.append(row)
            seed_fold_metrics.append(metrics)

            seed_y_true.append(fold_output["predictions"]["y_true"])
            seed_y_pred.append(fold_output["predictions"]["y_pred"])

            if prediction_dir is not None:
                pred_df = pd.DataFrame(
                    {
                        "seed": seed,
                        "fold_id": fold_id,
                        "event_id": fold_output["predictions"]["event_id"],
                        "t_us": fold_output["predictions"]["t_us"],
                        "rv_1s_true": fold_output["predictions"]["y_true"][:, 0],
                        "rv_5s_true": fold_output["predictions"]["y_true"][:, 1],
                        "rv_10s_true": fold_output["predictions"]["y_true"][:, 2],
                        "rv_1s_pred": fold_output["predictions"]["y_pred"][:, 0],
                        "rv_5s_pred": fold_output["predictions"]["y_pred"][:, 1],
                        "rv_10s_pred": fold_output["predictions"]["y_pred"][:, 2],
                    }
                )
                pred_df.to_parquet(
                    os.path.join(
                        prediction_dir,
                        f"{cfg.model_name}_seed_{seed}_fold_{fold_id:03d}.parquet",
                    ),
                    index=False,
                )

        if not seed_y_true:
            raise ValueError("No baseline test predictions were produced.")

        y_true = np.concatenate(seed_y_true, axis=0)
        y_pred = np.concatenate(seed_y_pred, axis=0)
        seed_row: Dict[str, object] = {"seed": int(seed)}
        for i, h in enumerate(RV_NAMES):
            seed_row[f"rmse_{h}"] = rmse(y_true[:, i], y_pred[:, i])
            seed_row[f"mae_{h}"] = mae(y_true[:, i], y_pred[:, i])
            seed_row[f"spearman_{h}"] = safe_spearman(y_pred[:, i], y_true[:, i])

        fold_diag = aggregate_rows(seed_fold_metrics)
        for metric_name, stats in fold_diag.items():
            if metric_name in seed_row:
                continue
            seed_row[f"{metric_name}_mean_across_folds"] = stats["mean"]
            seed_row[f"{metric_name}_std_across_folds"] = stats["std"]
        per_seed_rows.append(seed_row)

    # Aggregate across seeds using per-seed fold-averaged means
    overall_source_rows: List[Dict[str, float]] = []
    for row in per_seed_rows:
        reduced = {}
        for k, v in row.items():
            if k == "seed":
                continue
            if isinstance(v, (int, float, np.integer, np.floating)) and not k.endswith("_mean_across_folds") and not k.endswith("_std_across_folds"):
                reduced[k] = float(v)
        overall_source_rows.append(reduced)

    overall_metrics = aggregate_rows(overall_source_rows)

    summary = build_summary_json(
        cfg=cfg,
        fold_seed_rows=fold_seed_rows,
        per_seed_rows=per_seed_rows,
        overall_metrics=overall_metrics,
    )

    if cfg.out_dir is not None:
        seed_df = pd.DataFrame(per_seed_rows)
        summary_df = summary_dict_to_frame(overall_metrics)
        seed_df.to_csv(os.path.join(cfg.out_dir, "seed_metrics.csv"), index=False)
        summary_df.to_csv(os.path.join(cfg.out_dir, "summary_table.csv"), index=False)
        write_json(os.path.join(cfg.out_dir, "baseline_metrics_summary.json"), summary)
        manifest = build_run_manifest(
            args=None,
            config=cfg,
            repo_root=Path(__file__).resolve().parents[1],
            device=cfg.device,
            metadata={
                "model_name": cfg.model_name,
                "number_of_folds": int(len(fold_ids)),
                "fold_ids": [int(x) for x in fold_ids],
                "seeds": [int(x) for x in cfg.seeds],
                "output_paths": {
                    "seed_metrics": os.path.join(cfg.out_dir, "seed_metrics.csv"),
                    "summary_table": os.path.join(cfg.out_dir, "summary_table.csv"),
                    "baseline_metrics_summary": os.path.join(cfg.out_dir, "baseline_metrics_summary.json"),
                    "predictions": prediction_dir,
                },
                "elapsed_wall_clock_sec": time.time() - start_time,
                "peak_memory_gb": log_memory(f"after baseline {cfg.model_name}"),
            },
        )
        save_run_manifest(Path(cfg.out_dir) / "run_manifest.json", manifest)

    return summary


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------

def parse_seeds(seeds_str: Optional[str], num_seeds: int, base_seed: int) -> Tuple[int, ...]:
    if seeds_str:
        vals = [int(x.strip()) for x in seeds_str.split(",") if x.strip()]
        if len(vals) < 1 or len(vals) > 5:
            raise ValueError("Provide between 1 and 5 seeds.")
        return tuple(vals)

    if num_seeds < 1 or num_seeds > 5:
        raise ValueError("num_seeds must be between 1 and 5.")
    return tuple(base_seed + i for i in range(num_seeds))


def parse_args() -> RunnerConfig:
    parser = argparse.ArgumentParser(description="Train and evaluate DeepLOB / Static GCN baselines over discrete fold data.")
    parser.add_argument("--data-dir", required=True, help="Root directory produced by build_discrete_snapshots.py")
    parser.add_argument("--model-name", required=True, choices=["deeplob", "static_gcn"])
    parser.add_argument("--baselines-module-path", required=True, help="Path to baselines.py")

    parser.add_argument("--device", default="cpu")

    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--patience", type=int, default=5)
    parser.add_argument("--val-fraction", type=float, default=0.2)
    parser.add_argument("--min-val-samples", type=int, default=32)
    parser.add_argument("--purge-us", type=int, default=10_000_000)

    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--grad-clip-norm", type=float, default=1.0)

    parser.add_argument("--seeds", type=str, default=None)
    parser.add_argument("--num-seeds", type=int, default=3)
    parser.add_argument("--base-seed", type=int, default=42)

    parser.add_argument("--deeplob-input-dim", type=int, default=40)
    parser.add_argument("--deeplob-conv-channels", type=int, default=32)
    parser.add_argument("--deeplob-inception-branch-channels", type=int, default=16)
    parser.add_argument("--deeplob-lstm-hidden-dim", type=int, default=64)
    parser.add_argument("--deeplob-lstm-layers", type=int, default=1)
    parser.add_argument("--deeplob-regression-hidden-dim", type=int, default=128)
    parser.add_argument("--deeplob-dropout", type=float, default=0.1)

    parser.add_argument("--static-gcn-node-feat-dim", type=int, default=5)
    parser.add_argument("--static-gcn-num-levels", type=int, default=10)
    parser.add_argument("--static-gcn-hidden-dim", type=int, default=64)
    parser.add_argument("--static-gcn-num-layers", type=int, default=3)
    parser.add_argument("--static-gcn-dropout", type=float, default=0.1)
    parser.add_argument("--static-gcn-regression-hidden-dim", type=int, default=128)

    parser.add_argument("--out-dir", default=None)

    args = parser.parse_args()
    seeds = parse_seeds(args.seeds, args.num_seeds, args.base_seed)

    return RunnerConfig(
        data_dir=args.data_dir,
        baselines_module_path=args.baselines_module_path,
        model_name=args.model_name,
        device=args.device,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        epochs=args.epochs,
        patience=args.patience,
        val_fraction=args.val_fraction,
        min_val_samples=args.min_val_samples,
        purge_us=args.purge_us,
        lr=args.lr,
        weight_decay=args.weight_decay,
        grad_clip_norm=args.grad_clip_norm,
        seeds=seeds,
        deeplob_input_dim=args.deeplob_input_dim,
        deeplob_conv_channels=args.deeplob_conv_channels,
        deeplob_inception_branch_channels=args.deeplob_inception_branch_channels,
        deeplob_lstm_hidden_dim=args.deeplob_lstm_hidden_dim,
        deeplob_lstm_layers=args.deeplob_lstm_layers,
        deeplob_regression_hidden_dim=args.deeplob_regression_hidden_dim,
        deeplob_dropout=args.deeplob_dropout,
        static_gcn_node_feat_dim=args.static_gcn_node_feat_dim,
        static_gcn_num_levels=args.static_gcn_num_levels,
        static_gcn_hidden_dim=args.static_gcn_hidden_dim,
        static_gcn_num_layers=args.static_gcn_num_layers,
        static_gcn_dropout=args.static_gcn_dropout,
        static_gcn_regression_hidden_dim=args.static_gcn_regression_hidden_dim,
        out_dir=args.out_dir,
    )


def main() -> None:
    cfg = parse_args()
    summary = run_baseline_experiment(cfg)

    print(json.dumps(
        {
            "model_name": summary["model_name"],
            "overall_summary": summary["overall_summary"],
        },
        indent=2,
    ))


if __name__ == "__main__":
    main()
